/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
  #[serde(rename = "collectibleHash")]
  collectible_hash: Option<i32>
}

impl DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
  pub fn new() -> DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
    DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
      collectible_hash: None
    }
  }

  pub fn set_collectible_hash(&mut self, collectible_hash: i32) {
    self.collectible_hash = Some(collectible_hash);
  }

  pub fn with_collectible_hash(mut self, collectible_hash: i32) -> DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
    self.collectible_hash = Some(collectible_hash);
    self
  }

  pub fn collectible_hash(&self) -> Option<&i32> {
    self.collectible_hash.as_ref()
  }

  pub fn reset_collectible_hash(&mut self) {
    self.collectible_hash = None;
  }

}



