/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyMilestonesDestinyMilestone : Represents a runtime instance of a user's milestone status. Live Milestone data should be combined with DestinyMilestoneDefinition data to show the user a picture of what is available for them to do in the game, and their status in regards to said \"things to do.\" Consider it a big, wonky to-do list, or Advisors 3.0 for those who remember the Destiny 1 API.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyMilestonesDestinyMilestone {
  /// The unique identifier for the Milestone. Use it to look up the DestinyMilestoneDefinition, so you can combine the other data in this contract with static definition data.
  #[serde(rename = "milestoneHash")]
  milestone_hash: Option<i32>,
  /// Indicates what quests are available for this Milestone. Usually this will be only a single Quest, but some quests have multiple available that you can choose from at any given time. All possible quests for a milestone can be found in the DestinyMilestoneDefinition, but they must be combined with this Live data to determine which one(s) are actually active right now. It is possible for Milestones to not have any quests.
  #[serde(rename = "availableQuests")]
  available_quests: Option<Vec<::models::DestinyMilestonesDestinyMilestoneQuest>>,
  /// The currently active Activities in this milestone, when the Milestone is driven by Challenges.  Not all Milestones have Challenges, but when they do this will indicate the Activities and Challenges under those Activities related to this Milestone.
  #[serde(rename = "activities")]
  activities: Option<Vec<::models::DestinyMilestonesDestinyMilestoneChallengeActivity>>,
  /// Milestones may have arbitrary key/value pairs associated with them, for data that users will want to know about but that doesn't fit neatly into any of the common components such as Quests. A good example of this would be - if this existed in Destiny 1 - the number of wins you currently have on your Trials of Osiris ticket. Looking in the DestinyMilestoneDefinition, you can use the string identifier of this dictionary to look up more info about the value, including localized string content for displaying the value. The value in the dictionary is the floating point number. The definition will tell you how to format this number.
  #[serde(rename = "values")]
  values: Option<::std::collections::HashMap<String, f32>>,
  /// A milestone may have one or more active vendors that are \"related\" to it (that provide rewards, or that are the initiators of the Milestone). I already regret this, even as I'm typing it. [I told you I'd regret this] You see, sometimes a milestone may be directly correlated with a set of vendors that provide varying tiers of rewards. The player may not be able to interact with one or more of those vendors. This will return the hashes of the Vendors that the player *can* interact with, allowing you to show their current inventory as rewards or related items to the Milestone or its activities.  Before we even use it, it's already deprecated! How much of a bummer is that? We need more data.
  #[serde(rename = "vendorHashes")]
  vendor_hashes: Option<Vec<i32>>,
  /// Replaces vendorHashes, which I knew was going to be trouble the day it walked in the door. This will return not only what Vendors are active and relevant to the activity (in an implied order that you can choose to ignore), but also other data - for example, if the Vendor is featuring a specific item relevant to this event that you should show with them.
  #[serde(rename = "vendors")]
  vendors: Option<Vec<::models::DestinyMilestonesDestinyMilestoneVendor>>,
  /// If the entity to which this component is attached has known active Rewards for the player, this will detail information about those rewards, keyed by the RewardEntry Hash. (See DestinyMilestoneDefinition for more information about Reward Entries) Note that these rewards are not for the Quests related to the Milestone. Think of these as \"overview/checklist\" rewards that may be provided for Milestones that may provide rewards for performing a variety of tasks that aren't under a specific Quest.
  #[serde(rename = "rewards")]
  rewards: Option<Vec<::models::DestinyMilestonesDestinyMilestoneRewardCategory>>,
  /// If known, this is the date when the event last began or refreshed. It will only be populated for events with fixed and repeating start and end dates.
  #[serde(rename = "startDate")]
  start_date: Option<String>,
  /// If known, this is the date when the event will next end or repeat. It will only be populated for events with fixed and repeating start and end dates.
  #[serde(rename = "endDate")]
  end_date: Option<String>,
  /// Used for ordering milestones in a display to match how we order them in BNet. May pull from static data, or possibly in the future from dynamic information.
  #[serde(rename = "order")]
  order: Option<i32>
}

impl DestinyMilestonesDestinyMilestone {
  /// Represents a runtime instance of a user's milestone status. Live Milestone data should be combined with DestinyMilestoneDefinition data to show the user a picture of what is available for them to do in the game, and their status in regards to said \"things to do.\" Consider it a big, wonky to-do list, or Advisors 3.0 for those who remember the Destiny 1 API.
  pub fn new() -> DestinyMilestonesDestinyMilestone {
    DestinyMilestonesDestinyMilestone {
      milestone_hash: None,
      available_quests: None,
      activities: None,
      values: None,
      vendor_hashes: None,
      vendors: None,
      rewards: None,
      start_date: None,
      end_date: None,
      order: None
    }
  }

  pub fn set_milestone_hash(&mut self, milestone_hash: i32) {
    self.milestone_hash = Some(milestone_hash);
  }

  pub fn with_milestone_hash(mut self, milestone_hash: i32) -> DestinyMilestonesDestinyMilestone {
    self.milestone_hash = Some(milestone_hash);
    self
  }

  pub fn milestone_hash(&self) -> Option<&i32> {
    self.milestone_hash.as_ref()
  }

  pub fn reset_milestone_hash(&mut self) {
    self.milestone_hash = None;
  }

  pub fn set_available_quests(&mut self, available_quests: Vec<::models::DestinyMilestonesDestinyMilestoneQuest>) {
    self.available_quests = Some(available_quests);
  }

  pub fn with_available_quests(mut self, available_quests: Vec<::models::DestinyMilestonesDestinyMilestoneQuest>) -> DestinyMilestonesDestinyMilestone {
    self.available_quests = Some(available_quests);
    self
  }

  pub fn available_quests(&self) -> Option<&Vec<::models::DestinyMilestonesDestinyMilestoneQuest>> {
    self.available_quests.as_ref()
  }

  pub fn reset_available_quests(&mut self) {
    self.available_quests = None;
  }

  pub fn set_activities(&mut self, activities: Vec<::models::DestinyMilestonesDestinyMilestoneChallengeActivity>) {
    self.activities = Some(activities);
  }

  pub fn with_activities(mut self, activities: Vec<::models::DestinyMilestonesDestinyMilestoneChallengeActivity>) -> DestinyMilestonesDestinyMilestone {
    self.activities = Some(activities);
    self
  }

  pub fn activities(&self) -> Option<&Vec<::models::DestinyMilestonesDestinyMilestoneChallengeActivity>> {
    self.activities.as_ref()
  }

  pub fn reset_activities(&mut self) {
    self.activities = None;
  }

  pub fn set_values(&mut self, values: ::std::collections::HashMap<String, f32>) {
    self.values = Some(values);
  }

  pub fn with_values(mut self, values: ::std::collections::HashMap<String, f32>) -> DestinyMilestonesDestinyMilestone {
    self.values = Some(values);
    self
  }

  pub fn values(&self) -> Option<&::std::collections::HashMap<String, f32>> {
    self.values.as_ref()
  }

  pub fn reset_values(&mut self) {
    self.values = None;
  }

  pub fn set_vendor_hashes(&mut self, vendor_hashes: Vec<i32>) {
    self.vendor_hashes = Some(vendor_hashes);
  }

  pub fn with_vendor_hashes(mut self, vendor_hashes: Vec<i32>) -> DestinyMilestonesDestinyMilestone {
    self.vendor_hashes = Some(vendor_hashes);
    self
  }

  pub fn vendor_hashes(&self) -> Option<&Vec<i32>> {
    self.vendor_hashes.as_ref()
  }

  pub fn reset_vendor_hashes(&mut self) {
    self.vendor_hashes = None;
  }

  pub fn set_vendors(&mut self, vendors: Vec<::models::DestinyMilestonesDestinyMilestoneVendor>) {
    self.vendors = Some(vendors);
  }

  pub fn with_vendors(mut self, vendors: Vec<::models::DestinyMilestonesDestinyMilestoneVendor>) -> DestinyMilestonesDestinyMilestone {
    self.vendors = Some(vendors);
    self
  }

  pub fn vendors(&self) -> Option<&Vec<::models::DestinyMilestonesDestinyMilestoneVendor>> {
    self.vendors.as_ref()
  }

  pub fn reset_vendors(&mut self) {
    self.vendors = None;
  }

  pub fn set_rewards(&mut self, rewards: Vec<::models::DestinyMilestonesDestinyMilestoneRewardCategory>) {
    self.rewards = Some(rewards);
  }

  pub fn with_rewards(mut self, rewards: Vec<::models::DestinyMilestonesDestinyMilestoneRewardCategory>) -> DestinyMilestonesDestinyMilestone {
    self.rewards = Some(rewards);
    self
  }

  pub fn rewards(&self) -> Option<&Vec<::models::DestinyMilestonesDestinyMilestoneRewardCategory>> {
    self.rewards.as_ref()
  }

  pub fn reset_rewards(&mut self) {
    self.rewards = None;
  }

  pub fn set_start_date(&mut self, start_date: String) {
    self.start_date = Some(start_date);
  }

  pub fn with_start_date(mut self, start_date: String) -> DestinyMilestonesDestinyMilestone {
    self.start_date = Some(start_date);
    self
  }

  pub fn start_date(&self) -> Option<&String> {
    self.start_date.as_ref()
  }

  pub fn reset_start_date(&mut self) {
    self.start_date = None;
  }

  pub fn set_end_date(&mut self, end_date: String) {
    self.end_date = Some(end_date);
  }

  pub fn with_end_date(mut self, end_date: String) -> DestinyMilestonesDestinyMilestone {
    self.end_date = Some(end_date);
    self
  }

  pub fn end_date(&self) -> Option<&String> {
    self.end_date.as_ref()
  }

  pub fn reset_end_date(&mut self) {
    self.end_date = None;
  }

  pub fn set_order(&mut self, order: i32) {
    self.order = Some(order);
  }

  pub fn with_order(mut self, order: i32) -> DestinyMilestonesDestinyMilestone {
    self.order = Some(order);
    self
  }

  pub fn order(&self) -> Option<&i32> {
    self.order.as_ref()
  }

  pub fn reset_order(&mut self) {
    self.order = None;
  }

}



