/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsItemsDestinyItemPlugDefinition : If an item is a Plug, its DestinyInventoryItemDefinition.plug property will be populated with an instance of one of these bad boys.  This gives information about when it can be inserted, what the plug's category is (and thus whether it is compatible with a socket... see DestinySocketTypeDefinition for information about Plug Categories and socket compatibility), whether it is enabled and other Plug info.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsItemsDestinyItemPlugDefinition {
  /// The rules around when this plug can be inserted into a socket, aside from the socket's individual restrictions.  The live data DestinyItemPlugComponent.insertFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
  #[serde(rename = "insertionRules")]
  insertion_rules: Option<Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>>,
  /// The string identifier for the plug's category. Use the socket's DestinySocketTypeDefinition.plugWhitelist to determine whether this plug can be inserted into the socket.
  #[serde(rename = "plugCategoryIdentifier")]
  plug_category_identifier: Option<String>,
  /// The hash for the plugCategoryIdentifier. You can use this instead if you wish: I put both in the definition for debugging purposes.
  #[serde(rename = "plugCategoryHash")]
  plug_category_hash: Option<i32>,
  /// If you successfully socket the item, this will determine whether or not you get \"refunded\" on the plug.
  #[serde(rename = "onActionRecreateSelf")]
  on_action_recreate_self: Option<bool>,
  /// If inserting this plug requires materials, this is the hash identifier for looking up the DestinyMaterialRequirementSetDefinition for those requirements.
  #[serde(rename = "insertionMaterialRequirementHash")]
  insertion_material_requirement_hash: Option<i32>,
  /// In the game, if you're inspecting a plug item directly, this will be the item shown with the plug attached. Look up the DestinyInventoryItemDefinition for this hash for the item.
  #[serde(rename = "previewItemOverrideHash")]
  preview_item_override_hash: Option<i32>,
  /// It's not enough for the plug to be inserted. It has to be enabled as well. For it to be enabled, it may require materials. This is the hash identifier for the DestinyMaterialRequirementSetDefinition for those requirements, if there is one.
  #[serde(rename = "enabledMaterialRequirementHash")]
  enabled_material_requirement_hash: Option<i32>,
  /// The rules around whether the plug, once inserted, is enabled and providing its benefits.  The live data DestinyItemPlugComponent.enableFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
  #[serde(rename = "enabledRules")]
  enabled_rules: Option<Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>>,
  /// Plugs can have arbitrary, UI-defined identifiers that the UI designers use to determine the style applied to plugs. Unfortunately, we have neither a definitive list of these labels nor advance warning of when new labels might be applied or how that relates to how they get rendered. If you want to, you can refer to known labels to change your own styles: but know that new ones can be created arbitrarily, and we have no way of associating the labels with any specific UI style guidance... you'll have to piece that together on your end. Or do what we do, and just show plugs more generically, without specialized styles.
  #[serde(rename = "uiPlugLabel")]
  ui_plug_label: Option<String>,
  #[serde(rename = "plugStyle")]
  plug_style: Option<i32>,
  /// Indicates the rules about when this plug can be used. See the PlugAvailabilityMode enumeration for more information!
  #[serde(rename = "plugAvailability")]
  plug_availability: Option<i32>,
  /// If the plug meets certain state requirements, it may have an alternative label applied to it. This is the alternative label that will be applied in such a situation.
  #[serde(rename = "alternateUiPlugLabel")]
  alternate_ui_plug_label: Option<String>,
  /// The alternate plug of the plug: only applies when the item is in states that only the server can know about and control, unfortunately. See AlternateUiPlugLabel for the related label info.
  #[serde(rename = "alternatePlugStyle")]
  alternate_plug_style: Option<i32>,
  /// If TRUE, this plug is used for UI display purposes only, and doesn't have any interesting effects of its own.
  #[serde(rename = "isDummyPlug")]
  is_dummy_plug: Option<bool>,
  /// Do you ever get the feeling that a system has become so overburdened by edge cases that it probably should have become some other system entirely? So do I!  In totally unrelated news, Plugs can now override properties of their parent items. This is some of the relevant definition data for those overrides.  If this is populated, it will have the override data to be applied when this plug is applied to an item.
  #[serde(rename = "parentItemOverride")]
  parent_item_override: Option<Value>,
  /// IF not null, this plug provides Energy capacity to the item in which it is socketed. In Armor 2.0 for example, is implemented in a similar way to Masterworks, where visually it's a single area of the UI being clicked on to \"Upgrade\" to higher energy levels, but it's actually socketing new plugs.
  #[serde(rename = "energyCapacity")]
  energy_capacity: Option<Value>,
  /// IF not null, this plug has an energy cost. This contains the details of that cost.
  #[serde(rename = "energyCost")]
  energy_cost: Option<Value>
}

impl DestinyDefinitionsItemsDestinyItemPlugDefinition {
  /// If an item is a Plug, its DestinyInventoryItemDefinition.plug property will be populated with an instance of one of these bad boys.  This gives information about when it can be inserted, what the plug's category is (and thus whether it is compatible with a socket... see DestinySocketTypeDefinition for information about Plug Categories and socket compatibility), whether it is enabled and other Plug info.
  pub fn new() -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    DestinyDefinitionsItemsDestinyItemPlugDefinition {
      insertion_rules: None,
      plug_category_identifier: None,
      plug_category_hash: None,
      on_action_recreate_self: None,
      insertion_material_requirement_hash: None,
      preview_item_override_hash: None,
      enabled_material_requirement_hash: None,
      enabled_rules: None,
      ui_plug_label: None,
      plug_style: None,
      plug_availability: None,
      alternate_ui_plug_label: None,
      alternate_plug_style: None,
      is_dummy_plug: None,
      parent_item_override: None,
      energy_capacity: None,
      energy_cost: None
    }
  }

  pub fn set_insertion_rules(&mut self, insertion_rules: Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>) {
    self.insertion_rules = Some(insertion_rules);
  }

  pub fn with_insertion_rules(mut self, insertion_rules: Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.insertion_rules = Some(insertion_rules);
    self
  }

  pub fn insertion_rules(&self) -> Option<&Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>> {
    self.insertion_rules.as_ref()
  }

  pub fn reset_insertion_rules(&mut self) {
    self.insertion_rules = None;
  }

  pub fn set_plug_category_identifier(&mut self, plug_category_identifier: String) {
    self.plug_category_identifier = Some(plug_category_identifier);
  }

  pub fn with_plug_category_identifier(mut self, plug_category_identifier: String) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.plug_category_identifier = Some(plug_category_identifier);
    self
  }

  pub fn plug_category_identifier(&self) -> Option<&String> {
    self.plug_category_identifier.as_ref()
  }

  pub fn reset_plug_category_identifier(&mut self) {
    self.plug_category_identifier = None;
  }

  pub fn set_plug_category_hash(&mut self, plug_category_hash: i32) {
    self.plug_category_hash = Some(plug_category_hash);
  }

  pub fn with_plug_category_hash(mut self, plug_category_hash: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.plug_category_hash = Some(plug_category_hash);
    self
  }

  pub fn plug_category_hash(&self) -> Option<&i32> {
    self.plug_category_hash.as_ref()
  }

  pub fn reset_plug_category_hash(&mut self) {
    self.plug_category_hash = None;
  }

  pub fn set_on_action_recreate_self(&mut self, on_action_recreate_self: bool) {
    self.on_action_recreate_self = Some(on_action_recreate_self);
  }

  pub fn with_on_action_recreate_self(mut self, on_action_recreate_self: bool) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.on_action_recreate_self = Some(on_action_recreate_self);
    self
  }

  pub fn on_action_recreate_self(&self) -> Option<&bool> {
    self.on_action_recreate_self.as_ref()
  }

  pub fn reset_on_action_recreate_self(&mut self) {
    self.on_action_recreate_self = None;
  }

  pub fn set_insertion_material_requirement_hash(&mut self, insertion_material_requirement_hash: i32) {
    self.insertion_material_requirement_hash = Some(insertion_material_requirement_hash);
  }

  pub fn with_insertion_material_requirement_hash(mut self, insertion_material_requirement_hash: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.insertion_material_requirement_hash = Some(insertion_material_requirement_hash);
    self
  }

  pub fn insertion_material_requirement_hash(&self) -> Option<&i32> {
    self.insertion_material_requirement_hash.as_ref()
  }

  pub fn reset_insertion_material_requirement_hash(&mut self) {
    self.insertion_material_requirement_hash = None;
  }

  pub fn set_preview_item_override_hash(&mut self, preview_item_override_hash: i32) {
    self.preview_item_override_hash = Some(preview_item_override_hash);
  }

  pub fn with_preview_item_override_hash(mut self, preview_item_override_hash: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.preview_item_override_hash = Some(preview_item_override_hash);
    self
  }

  pub fn preview_item_override_hash(&self) -> Option<&i32> {
    self.preview_item_override_hash.as_ref()
  }

  pub fn reset_preview_item_override_hash(&mut self) {
    self.preview_item_override_hash = None;
  }

  pub fn set_enabled_material_requirement_hash(&mut self, enabled_material_requirement_hash: i32) {
    self.enabled_material_requirement_hash = Some(enabled_material_requirement_hash);
  }

  pub fn with_enabled_material_requirement_hash(mut self, enabled_material_requirement_hash: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.enabled_material_requirement_hash = Some(enabled_material_requirement_hash);
    self
  }

  pub fn enabled_material_requirement_hash(&self) -> Option<&i32> {
    self.enabled_material_requirement_hash.as_ref()
  }

  pub fn reset_enabled_material_requirement_hash(&mut self) {
    self.enabled_material_requirement_hash = None;
  }

  pub fn set_enabled_rules(&mut self, enabled_rules: Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>) {
    self.enabled_rules = Some(enabled_rules);
  }

  pub fn with_enabled_rules(mut self, enabled_rules: Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.enabled_rules = Some(enabled_rules);
    self
  }

  pub fn enabled_rules(&self) -> Option<&Vec<::models::DestinyDefinitionsItemsDestinyPlugRuleDefinition>> {
    self.enabled_rules.as_ref()
  }

  pub fn reset_enabled_rules(&mut self) {
    self.enabled_rules = None;
  }

  pub fn set_ui_plug_label(&mut self, ui_plug_label: String) {
    self.ui_plug_label = Some(ui_plug_label);
  }

  pub fn with_ui_plug_label(mut self, ui_plug_label: String) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.ui_plug_label = Some(ui_plug_label);
    self
  }

  pub fn ui_plug_label(&self) -> Option<&String> {
    self.ui_plug_label.as_ref()
  }

  pub fn reset_ui_plug_label(&mut self) {
    self.ui_plug_label = None;
  }

  pub fn set_plug_style(&mut self, plug_style: i32) {
    self.plug_style = Some(plug_style);
  }

  pub fn with_plug_style(mut self, plug_style: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.plug_style = Some(plug_style);
    self
  }

  pub fn plug_style(&self) -> Option<&i32> {
    self.plug_style.as_ref()
  }

  pub fn reset_plug_style(&mut self) {
    self.plug_style = None;
  }

  pub fn set_plug_availability(&mut self, plug_availability: i32) {
    self.plug_availability = Some(plug_availability);
  }

  pub fn with_plug_availability(mut self, plug_availability: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.plug_availability = Some(plug_availability);
    self
  }

  pub fn plug_availability(&self) -> Option<&i32> {
    self.plug_availability.as_ref()
  }

  pub fn reset_plug_availability(&mut self) {
    self.plug_availability = None;
  }

  pub fn set_alternate_ui_plug_label(&mut self, alternate_ui_plug_label: String) {
    self.alternate_ui_plug_label = Some(alternate_ui_plug_label);
  }

  pub fn with_alternate_ui_plug_label(mut self, alternate_ui_plug_label: String) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.alternate_ui_plug_label = Some(alternate_ui_plug_label);
    self
  }

  pub fn alternate_ui_plug_label(&self) -> Option<&String> {
    self.alternate_ui_plug_label.as_ref()
  }

  pub fn reset_alternate_ui_plug_label(&mut self) {
    self.alternate_ui_plug_label = None;
  }

  pub fn set_alternate_plug_style(&mut self, alternate_plug_style: i32) {
    self.alternate_plug_style = Some(alternate_plug_style);
  }

  pub fn with_alternate_plug_style(mut self, alternate_plug_style: i32) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.alternate_plug_style = Some(alternate_plug_style);
    self
  }

  pub fn alternate_plug_style(&self) -> Option<&i32> {
    self.alternate_plug_style.as_ref()
  }

  pub fn reset_alternate_plug_style(&mut self) {
    self.alternate_plug_style = None;
  }

  pub fn set_is_dummy_plug(&mut self, is_dummy_plug: bool) {
    self.is_dummy_plug = Some(is_dummy_plug);
  }

  pub fn with_is_dummy_plug(mut self, is_dummy_plug: bool) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.is_dummy_plug = Some(is_dummy_plug);
    self
  }

  pub fn is_dummy_plug(&self) -> Option<&bool> {
    self.is_dummy_plug.as_ref()
  }

  pub fn reset_is_dummy_plug(&mut self) {
    self.is_dummy_plug = None;
  }

  pub fn set_parent_item_override(&mut self, parent_item_override: Value) {
    self.parent_item_override = Some(parent_item_override);
  }

  pub fn with_parent_item_override(mut self, parent_item_override: Value) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.parent_item_override = Some(parent_item_override);
    self
  }

  pub fn parent_item_override(&self) -> Option<&Value> {
    self.parent_item_override.as_ref()
  }

  pub fn reset_parent_item_override(&mut self) {
    self.parent_item_override = None;
  }

  pub fn set_energy_capacity(&mut self, energy_capacity: Value) {
    self.energy_capacity = Some(energy_capacity);
  }

  pub fn with_energy_capacity(mut self, energy_capacity: Value) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.energy_capacity = Some(energy_capacity);
    self
  }

  pub fn energy_capacity(&self) -> Option<&Value> {
    self.energy_capacity.as_ref()
  }

  pub fn reset_energy_capacity(&mut self) {
    self.energy_capacity = None;
  }

  pub fn set_energy_cost(&mut self, energy_cost: Value) {
    self.energy_cost = Some(energy_cost);
  }

  pub fn with_energy_cost(mut self, energy_cost: Value) -> DestinyDefinitionsItemsDestinyItemPlugDefinition {
    self.energy_cost = Some(energy_cost);
    self
  }

  pub fn energy_cost(&self) -> Option<&Value> {
    self.energy_cost.as_ref()
  }

  pub fn reset_energy_cost(&mut self) {
    self.energy_cost = None;
  }

}



