/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsDestinyProgressionDefinition : A \"Progression\" in Destiny is best explained by an example.  A Character's \"Level\" is a progression: it has Experience that can be earned, levels that can be gained, and is evaluated and displayed at various points in the game. A Character's \"Faction Reputation\" is also a progression for much the same reason.  Progression is used by a variety of systems, and the definition of a Progression will generally only be useful if combining with live data (such as a character's DestinyCharacterProgressionComponent.progressions property, which holds that character's live Progression states).  Fundamentally, a Progression measures your \"Level\" by evaluating the thresholds in its Steps (one step per level, except for the last step which can be repeated indefinitely for \"Levels\" that have no ceiling) against the total earned \"progression points\"/experience. (for simplicity purposes, we will henceforth refer to earned progression points as experience, though it need not be a mechanic that in any way resembles Experience in a traditional sense).  Earned experience is calculated in a variety of ways, determined by the Progression's scope. These go from looking up a stored value to performing exceedingly obtuse calculations. This is why we provide live data in DestinyCharacterProgressionComponent.progressions, so you don't have to worry about those.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyProgressionDefinition {
  #[serde(rename = "displayProperties")]
  display_properties: Option<::models::DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition>,
  /// The \"Scope\" of the progression indicates the source of the progression's live data.  See the DestinyProgressionScope enum for more info: but essentially, a Progression can either be backed by a stored value, or it can be a calculated derivative of other values.
  #[serde(rename = "scope")]
  scope: Option<i32>,
  /// If this is True, then the progression doesn't have a maximum level.
  #[serde(rename = "repeatLastStep")]
  repeat_last_step: Option<bool>,
  /// If there's a description of how to earn this progression in the local config, this will be that localized description.
  #[serde(rename = "source")]
  source: Option<String>,
  /// Progressions are divided into Steps, which roughly equate to \"Levels\" in the traditional sense of a Progression. Notably, the last step can be repeated indefinitely if repeatLastStep is true, meaning that the calculation for your level is not as simple as comparing your current progress to the max progress of the steps.   These and more calculations are done for you if you grab live character progression data, such as in the DestinyCharacterProgressionComponent.
  #[serde(rename = "steps")]
  steps: Option<Vec<::models::DestinyDefinitionsDestinyProgressionStepDefinition>>,
  /// If true, the Progression is something worth showing to users.  If false, BNet isn't going to show it. But that doesn't mean you can't. We're all friends here.
  #[serde(rename = "visible")]
  visible: Option<bool>,
  /// If the value exists, this is the hash identifier for the Faction that owns this Progression.  This is purely for convenience, if you're looking at a progression and want to know if and who it's related to in terms of Faction Reputation.
  #[serde(rename = "factionHash")]
  faction_hash: Option<i32>,
  /// The #RGB string value for the color related to this progression, if there is one.
  #[serde(rename = "color")]
  color: Option<Value>,
  /// For progressions that have it, this is the rank icon we use in the Companion, displayed above the progressions' rank value.
  #[serde(rename = "rankIcon")]
  rank_icon: Option<String>,
  #[serde(rename = "rewardItems")]
  reward_items: Option<Vec<::models::DestinyDefinitionsDestinyProgressionRewardItemQuantity>>,
  /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
  #[serde(rename = "hash")]
  hash: Option<i32>,
  /// The index of the entity as it was found in the investment tables.
  #[serde(rename = "index")]
  index: Option<i32>,
  /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
  #[serde(rename = "redacted")]
  redacted: Option<bool>
}

impl DestinyDefinitionsDestinyProgressionDefinition {
  /// A \"Progression\" in Destiny is best explained by an example.  A Character's \"Level\" is a progression: it has Experience that can be earned, levels that can be gained, and is evaluated and displayed at various points in the game. A Character's \"Faction Reputation\" is also a progression for much the same reason.  Progression is used by a variety of systems, and the definition of a Progression will generally only be useful if combining with live data (such as a character's DestinyCharacterProgressionComponent.progressions property, which holds that character's live Progression states).  Fundamentally, a Progression measures your \"Level\" by evaluating the thresholds in its Steps (one step per level, except for the last step which can be repeated indefinitely for \"Levels\" that have no ceiling) against the total earned \"progression points\"/experience. (for simplicity purposes, we will henceforth refer to earned progression points as experience, though it need not be a mechanic that in any way resembles Experience in a traditional sense).  Earned experience is calculated in a variety of ways, determined by the Progression's scope. These go from looking up a stored value to performing exceedingly obtuse calculations. This is why we provide live data in DestinyCharacterProgressionComponent.progressions, so you don't have to worry about those.
  pub fn new() -> DestinyDefinitionsDestinyProgressionDefinition {
    DestinyDefinitionsDestinyProgressionDefinition {
      display_properties: None,
      scope: None,
      repeat_last_step: None,
      source: None,
      steps: None,
      visible: None,
      faction_hash: None,
      color: None,
      rank_icon: None,
      reward_items: None,
      hash: None,
      index: None,
      redacted: None
    }
  }

  pub fn set_display_properties(&mut self, display_properties: ::models::DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition) {
    self.display_properties = Some(display_properties);
  }

  pub fn with_display_properties(mut self, display_properties: ::models::DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.display_properties = Some(display_properties);
    self
  }

  pub fn display_properties(&self) -> Option<&::models::DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition> {
    self.display_properties.as_ref()
  }

  pub fn reset_display_properties(&mut self) {
    self.display_properties = None;
  }

  pub fn set_scope(&mut self, scope: i32) {
    self.scope = Some(scope);
  }

  pub fn with_scope(mut self, scope: i32) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.scope = Some(scope);
    self
  }

  pub fn scope(&self) -> Option<&i32> {
    self.scope.as_ref()
  }

  pub fn reset_scope(&mut self) {
    self.scope = None;
  }

  pub fn set_repeat_last_step(&mut self, repeat_last_step: bool) {
    self.repeat_last_step = Some(repeat_last_step);
  }

  pub fn with_repeat_last_step(mut self, repeat_last_step: bool) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.repeat_last_step = Some(repeat_last_step);
    self
  }

  pub fn repeat_last_step(&self) -> Option<&bool> {
    self.repeat_last_step.as_ref()
  }

  pub fn reset_repeat_last_step(&mut self) {
    self.repeat_last_step = None;
  }

  pub fn set_source(&mut self, source: String) {
    self.source = Some(source);
  }

  pub fn with_source(mut self, source: String) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.source = Some(source);
    self
  }

  pub fn source(&self) -> Option<&String> {
    self.source.as_ref()
  }

  pub fn reset_source(&mut self) {
    self.source = None;
  }

  pub fn set_steps(&mut self, steps: Vec<::models::DestinyDefinitionsDestinyProgressionStepDefinition>) {
    self.steps = Some(steps);
  }

  pub fn with_steps(mut self, steps: Vec<::models::DestinyDefinitionsDestinyProgressionStepDefinition>) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.steps = Some(steps);
    self
  }

  pub fn steps(&self) -> Option<&Vec<::models::DestinyDefinitionsDestinyProgressionStepDefinition>> {
    self.steps.as_ref()
  }

  pub fn reset_steps(&mut self) {
    self.steps = None;
  }

  pub fn set_visible(&mut self, visible: bool) {
    self.visible = Some(visible);
  }

  pub fn with_visible(mut self, visible: bool) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.visible = Some(visible);
    self
  }

  pub fn visible(&self) -> Option<&bool> {
    self.visible.as_ref()
  }

  pub fn reset_visible(&mut self) {
    self.visible = None;
  }

  pub fn set_faction_hash(&mut self, faction_hash: i32) {
    self.faction_hash = Some(faction_hash);
  }

  pub fn with_faction_hash(mut self, faction_hash: i32) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.faction_hash = Some(faction_hash);
    self
  }

  pub fn faction_hash(&self) -> Option<&i32> {
    self.faction_hash.as_ref()
  }

  pub fn reset_faction_hash(&mut self) {
    self.faction_hash = None;
  }

  pub fn set_color(&mut self, color: Value) {
    self.color = Some(color);
  }

  pub fn with_color(mut self, color: Value) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.color = Some(color);
    self
  }

  pub fn color(&self) -> Option<&Value> {
    self.color.as_ref()
  }

  pub fn reset_color(&mut self) {
    self.color = None;
  }

  pub fn set_rank_icon(&mut self, rank_icon: String) {
    self.rank_icon = Some(rank_icon);
  }

  pub fn with_rank_icon(mut self, rank_icon: String) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.rank_icon = Some(rank_icon);
    self
  }

  pub fn rank_icon(&self) -> Option<&String> {
    self.rank_icon.as_ref()
  }

  pub fn reset_rank_icon(&mut self) {
    self.rank_icon = None;
  }

  pub fn set_reward_items(&mut self, reward_items: Vec<::models::DestinyDefinitionsDestinyProgressionRewardItemQuantity>) {
    self.reward_items = Some(reward_items);
  }

  pub fn with_reward_items(mut self, reward_items: Vec<::models::DestinyDefinitionsDestinyProgressionRewardItemQuantity>) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.reward_items = Some(reward_items);
    self
  }

  pub fn reward_items(&self) -> Option<&Vec<::models::DestinyDefinitionsDestinyProgressionRewardItemQuantity>> {
    self.reward_items.as_ref()
  }

  pub fn reset_reward_items(&mut self) {
    self.reward_items = None;
  }

  pub fn set_hash(&mut self, hash: i32) {
    self.hash = Some(hash);
  }

  pub fn with_hash(mut self, hash: i32) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.hash = Some(hash);
    self
  }

  pub fn hash(&self) -> Option<&i32> {
    self.hash.as_ref()
  }

  pub fn reset_hash(&mut self) {
    self.hash = None;
  }

  pub fn set_index(&mut self, index: i32) {
    self.index = Some(index);
  }

  pub fn with_index(mut self, index: i32) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.index = Some(index);
    self
  }

  pub fn index(&self) -> Option<&i32> {
    self.index.as_ref()
  }

  pub fn reset_index(&mut self) {
    self.index = None;
  }

  pub fn set_redacted(&mut self, redacted: bool) {
    self.redacted = Some(redacted);
  }

  pub fn with_redacted(mut self, redacted: bool) -> DestinyDefinitionsDestinyProgressionDefinition {
    self.redacted = Some(redacted);
    self
  }

  pub fn redacted(&self) -> Option<&bool> {
    self.redacted.as_ref()
  }

  pub fn reset_redacted(&mut self) {
    self.redacted = None;
  }

}



