/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyResponsesPersonalDestinyVendorSaleItemSetComponent {
  #[serde(rename = "saleItems")]
  sale_items: Option<::std::collections::HashMap<String, ::models::DestinyEntitiesVendorsDestinyVendorSaleItemComponent>>
}

impl DestinyResponsesPersonalDestinyVendorSaleItemSetComponent {
  pub fn new() -> DestinyResponsesPersonalDestinyVendorSaleItemSetComponent {
    DestinyResponsesPersonalDestinyVendorSaleItemSetComponent {
      sale_items: None
    }
  }

  pub fn set_sale_items(&mut self, sale_items: ::std::collections::HashMap<String, ::models::DestinyEntitiesVendorsDestinyVendorSaleItemComponent>) {
    self.sale_items = Some(sale_items);
  }

  pub fn with_sale_items(mut self, sale_items: ::std::collections::HashMap<String, ::models::DestinyEntitiesVendorsDestinyVendorSaleItemComponent>) -> DestinyResponsesPersonalDestinyVendorSaleItemSetComponent {
    self.sale_items = Some(sale_items);
    self
  }

  pub fn sale_items(&self) -> Option<&::std::collections::HashMap<String, ::models::DestinyEntitiesVendorsDestinyVendorSaleItemComponent>> {
    self.sale_items.as_ref()
  }

  pub fn reset_sale_items(&mut self) {
    self.sale_items = None;
  }

}



