/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDestinyPresentationScreenStyle : A hint for what screen should be shown when this presentation node is clicked into. How you use this is your UI is up to you.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDestinyPresentationScreenStyle {
}

impl DestinyDestinyPresentationScreenStyle {
  /// A hint for what screen should be shown when this presentation node is clicked into. How you use this is your UI is up to you.
  pub fn new() -> DestinyDestinyPresentationScreenStyle {
    DestinyDestinyPresentationScreenStyle {
    }
  }

}

// TODO enum 
// List of Destiny.DestinyPresentationScreenStyle
//const (
//  
//  
//  
//)


