/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
  #[serde(rename = "currencyItemHash")]
  currency_item_hash: Option<i32>,
  #[serde(rename = "scalarValue")]
  scalar_value: Option<i32>
}

impl DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
  pub fn new() -> DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
    DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
      currency_item_hash: None,
      scalar_value: None
    }
  }

  pub fn set_currency_item_hash(&mut self, currency_item_hash: i32) {
    self.currency_item_hash = Some(currency_item_hash);
  }

  pub fn with_currency_item_hash(mut self, currency_item_hash: i32) -> DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
    self.currency_item_hash = Some(currency_item_hash);
    self
  }

  pub fn currency_item_hash(&self) -> Option<&i32> {
    self.currency_item_hash.as_ref()
  }

  pub fn reset_currency_item_hash(&mut self) {
    self.currency_item_hash = None;
  }

  pub fn set_scalar_value(&mut self, scalar_value: i32) {
    self.scalar_value = Some(scalar_value);
  }

  pub fn with_scalar_value(mut self, scalar_value: i32) -> DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
    self.scalar_value = Some(scalar_value);
    self
  }

  pub fn scalar_value(&self) -> Option<&i32> {
    self.scalar_value.as_ref()
  }

  pub fn reset_scalar_value(&mut self) {
    self.scalar_value = None;
  }

}



