/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyPlugUiStyles : If the plug has a specific custom style, this enumeration will represent that style/those styles.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyPlugUiStyles {
}

impl DestinyPlugUiStyles {
  /// If the plug has a specific custom style, this enumeration will represent that style/those styles.
  pub fn new() -> DestinyPlugUiStyles {
    DestinyPlugUiStyles {
    }
  }

}

// TODO enum 
// List of Destiny.PlugUiStyles
//const (
//  
//  
//  
//)


