/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyAdvancedAwaResponseReason {
}

impl DestinyAdvancedAwaResponseReason {
  pub fn new() -> DestinyAdvancedAwaResponseReason {
    DestinyAdvancedAwaResponseReason {
    }
  }

}

// TODO enum 
// List of Destiny.Advanced.AwaResponseReason
//const (
//  
//  
//  
//)


