/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDestinyProgressionStepDisplayEffect : If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDestinyProgressionStepDisplayEffect {
}

impl DestinyDestinyProgressionStepDisplayEffect {
  /// If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.
  pub fn new() -> DestinyDestinyProgressionStepDisplayEffect {
    DestinyDestinyProgressionStepDisplayEffect {
    }
  }

}

// TODO enum 
// List of Destiny.DestinyProgressionStepDisplayEffect
//const (
//  
//  
//  
//)


