/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DestinyDefinitionsDestinyNodeStepDefinition : This defines the properties of a \"Talent Node Step\". When you see a talent node in game, the actual visible properties that you see (its icon, description, the perks and stats it provides) are not provided by the Node itself, but rather by the currently active Step on the node.  When a Talent Node is activated, the currently active step's benefits are conferred upon the item and character.  The currently active step on talent nodes are determined when an item is first instantiated. Sometimes it is random, sometimes it is more deterministic (particularly when a node has only a single step).  Note that, when dealing with Talent Node Steps, you must ensure that you have the latest version of content. stepIndex and nodeStepHash - two ways of identifying the step within a node - are both content version dependent, and thus are subject to change between content updates.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyNodeStepDefinition {
  /// These are the display properties actually used to render the Talent Node. The currently active step's displayProperties are shown.
  #[serde(rename = "displayProperties")]
  display_properties: Option<Value>,
  /// The index of this step in the list of Steps on the Talent Node.  Unfortunately, this is the closest thing we have to an identifier for the Step: steps are not provided a content version agnostic identifier. This means that, when you are dealing with talent nodes, you will need to first ensure that you have the latest version of content.
  #[serde(rename = "stepIndex")]
  step_index: Option<i32>,
  /// The hash of this node step. Unfortunately, while it can be used to uniquely identify the step within a node, it is also content version dependent and should not be relied on without ensuring you have the latest vesion of content.
  #[serde(rename = "nodeStepHash")]
  node_step_hash: Option<i32>,
  /// If you can interact with this node in some way, this is the localized description of that interaction.
  #[serde(rename = "interactionDescription")]
  interaction_description: Option<String>,
  /// An enum representing a damage type granted by activating this step, if any.
  #[serde(rename = "damageType")]
  damage_type: Option<i32>,
  /// If the step provides a damage type, this will be the hash identifier used to look up the damage type's DestinyDamageTypeDefinition.
  #[serde(rename = "damageTypeHash")]
  damage_type_hash: Option<i32>,
  /// If the step has requirements for activation (they almost always do, if nothing else than for the Talent Grid's Progression to have reached a certain level), they will be defined here.
  #[serde(rename = "activationRequirement")]
  activation_requirement: Option<Value>,
  /// There was a time when talent nodes could be activated multiple times, and the effects of subsequent Steps would be compounded on each other, essentially \"upgrading\" the node. We have moved away from this, but theoretically the capability still exists.  I continue to return this in case it is used in the future: if true and this step is the current step in the node, you are allowed to activate the node a second time to receive the benefits of the next step in the node, which will then become the active step.
  #[serde(rename = "canActivateNextStep")]
  can_activate_next_step: Option<bool>,
  /// The stepIndex of the next step in the talent node, or -1 if this is the last step or if the next step to be chosen is random.  This doesn't really matter anymore unless canActivateNextStep begins to be used again.
  #[serde(rename = "nextStepIndex")]
  next_step_index: Option<i32>,
  /// If true, the next step to be chosen is random, and if you're allowed to activate the next step. (if canActivateNextStep = true)
  #[serde(rename = "isNextStepRandom")]
  is_next_step_random: Option<bool>,
  /// The list of hash identifiers for Perks (DestinySandboxPerkDefinition) that are applied when this step is active. Perks provide a variety of benefits and modifications - examine DestinySandboxPerkDefinition to learn more.
  #[serde(rename = "perkHashes")]
  perk_hashes: Option<Vec<i32>>,
  /// When the Talent Grid's progression reaches this value, the circular \"progress bar\" that surrounds the talent node should be shown.  This also indicates the lower bound of said progress bar, with the upper bound being the progress required to reach activationRequirement.gridLevel. (at some point I should precalculate the upper bound and put it in the definition to save people time)
  #[serde(rename = "startProgressionBarAtProgress")]
  start_progression_bar_at_progress: Option<i32>,
  /// When the step provides stat benefits on the item or character, this is the list of hash identifiers for stats (DestinyStatDefinition) that are provided.
  #[serde(rename = "statHashes")]
  stat_hashes: Option<Vec<i32>>,
  /// If this is true, the step affects the item's Quality in some way. See DestinyInventoryItemDefinition for more information about the meaning of Quality. I already made a joke about Zen and the Art of Motorcycle Maintenance elsewhere in the documentation, so I will avoid doing it again. Oops too late
  #[serde(rename = "affectsQuality")]
  affects_quality: Option<bool>,
  /// In Destiny 1, the Armory's Perk Filtering was driven by a concept of TalentNodeStepGroups: categorizations of talent nodes based on their functionality. While the Armory isn't a BNet-facing thing for now, and the new Armory will need to account for Sockets rather than Talent Nodes, this categorization capability feels useful enough to still keep around.
  #[serde(rename = "stepGroups")]
  step_groups: Option<Value>,
  /// If true, this step can affect the level of the item. See DestinyInventoryItemDefintion for more information about item levels and their effect on stats.
  #[serde(rename = "affectsLevel")]
  affects_level: Option<bool>,
  /// If this step is activated, this will be a list of information used to replace socket items with new Plugs. See DestinyInventoryItemDefinition for more information about sockets and plugs.
  #[serde(rename = "socketReplacements")]
  socket_replacements: Option<Vec<::models::DestinyDefinitionsDestinyNodeSocketReplaceResponse>>
}

impl DestinyDefinitionsDestinyNodeStepDefinition {
  /// This defines the properties of a \"Talent Node Step\". When you see a talent node in game, the actual visible properties that you see (its icon, description, the perks and stats it provides) are not provided by the Node itself, but rather by the currently active Step on the node.  When a Talent Node is activated, the currently active step's benefits are conferred upon the item and character.  The currently active step on talent nodes are determined when an item is first instantiated. Sometimes it is random, sometimes it is more deterministic (particularly when a node has only a single step).  Note that, when dealing with Talent Node Steps, you must ensure that you have the latest version of content. stepIndex and nodeStepHash - two ways of identifying the step within a node - are both content version dependent, and thus are subject to change between content updates.
  pub fn new() -> DestinyDefinitionsDestinyNodeStepDefinition {
    DestinyDefinitionsDestinyNodeStepDefinition {
      display_properties: None,
      step_index: None,
      node_step_hash: None,
      interaction_description: None,
      damage_type: None,
      damage_type_hash: None,
      activation_requirement: None,
      can_activate_next_step: None,
      next_step_index: None,
      is_next_step_random: None,
      perk_hashes: None,
      start_progression_bar_at_progress: None,
      stat_hashes: None,
      affects_quality: None,
      step_groups: None,
      affects_level: None,
      socket_replacements: None
    }
  }

  pub fn set_display_properties(&mut self, display_properties: Value) {
    self.display_properties = Some(display_properties);
  }

  pub fn with_display_properties(mut self, display_properties: Value) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.display_properties = Some(display_properties);
    self
  }

  pub fn display_properties(&self) -> Option<&Value> {
    self.display_properties.as_ref()
  }

  pub fn reset_display_properties(&mut self) {
    self.display_properties = None;
  }

  pub fn set_step_index(&mut self, step_index: i32) {
    self.step_index = Some(step_index);
  }

  pub fn with_step_index(mut self, step_index: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.step_index = Some(step_index);
    self
  }

  pub fn step_index(&self) -> Option<&i32> {
    self.step_index.as_ref()
  }

  pub fn reset_step_index(&mut self) {
    self.step_index = None;
  }

  pub fn set_node_step_hash(&mut self, node_step_hash: i32) {
    self.node_step_hash = Some(node_step_hash);
  }

  pub fn with_node_step_hash(mut self, node_step_hash: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.node_step_hash = Some(node_step_hash);
    self
  }

  pub fn node_step_hash(&self) -> Option<&i32> {
    self.node_step_hash.as_ref()
  }

  pub fn reset_node_step_hash(&mut self) {
    self.node_step_hash = None;
  }

  pub fn set_interaction_description(&mut self, interaction_description: String) {
    self.interaction_description = Some(interaction_description);
  }

  pub fn with_interaction_description(mut self, interaction_description: String) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.interaction_description = Some(interaction_description);
    self
  }

  pub fn interaction_description(&self) -> Option<&String> {
    self.interaction_description.as_ref()
  }

  pub fn reset_interaction_description(&mut self) {
    self.interaction_description = None;
  }

  pub fn set_damage_type(&mut self, damage_type: i32) {
    self.damage_type = Some(damage_type);
  }

  pub fn with_damage_type(mut self, damage_type: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.damage_type = Some(damage_type);
    self
  }

  pub fn damage_type(&self) -> Option<&i32> {
    self.damage_type.as_ref()
  }

  pub fn reset_damage_type(&mut self) {
    self.damage_type = None;
  }

  pub fn set_damage_type_hash(&mut self, damage_type_hash: i32) {
    self.damage_type_hash = Some(damage_type_hash);
  }

  pub fn with_damage_type_hash(mut self, damage_type_hash: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.damage_type_hash = Some(damage_type_hash);
    self
  }

  pub fn damage_type_hash(&self) -> Option<&i32> {
    self.damage_type_hash.as_ref()
  }

  pub fn reset_damage_type_hash(&mut self) {
    self.damage_type_hash = None;
  }

  pub fn set_activation_requirement(&mut self, activation_requirement: Value) {
    self.activation_requirement = Some(activation_requirement);
  }

  pub fn with_activation_requirement(mut self, activation_requirement: Value) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.activation_requirement = Some(activation_requirement);
    self
  }

  pub fn activation_requirement(&self) -> Option<&Value> {
    self.activation_requirement.as_ref()
  }

  pub fn reset_activation_requirement(&mut self) {
    self.activation_requirement = None;
  }

  pub fn set_can_activate_next_step(&mut self, can_activate_next_step: bool) {
    self.can_activate_next_step = Some(can_activate_next_step);
  }

  pub fn with_can_activate_next_step(mut self, can_activate_next_step: bool) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.can_activate_next_step = Some(can_activate_next_step);
    self
  }

  pub fn can_activate_next_step(&self) -> Option<&bool> {
    self.can_activate_next_step.as_ref()
  }

  pub fn reset_can_activate_next_step(&mut self) {
    self.can_activate_next_step = None;
  }

  pub fn set_next_step_index(&mut self, next_step_index: i32) {
    self.next_step_index = Some(next_step_index);
  }

  pub fn with_next_step_index(mut self, next_step_index: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.next_step_index = Some(next_step_index);
    self
  }

  pub fn next_step_index(&self) -> Option<&i32> {
    self.next_step_index.as_ref()
  }

  pub fn reset_next_step_index(&mut self) {
    self.next_step_index = None;
  }

  pub fn set_is_next_step_random(&mut self, is_next_step_random: bool) {
    self.is_next_step_random = Some(is_next_step_random);
  }

  pub fn with_is_next_step_random(mut self, is_next_step_random: bool) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.is_next_step_random = Some(is_next_step_random);
    self
  }

  pub fn is_next_step_random(&self) -> Option<&bool> {
    self.is_next_step_random.as_ref()
  }

  pub fn reset_is_next_step_random(&mut self) {
    self.is_next_step_random = None;
  }

  pub fn set_perk_hashes(&mut self, perk_hashes: Vec<i32>) {
    self.perk_hashes = Some(perk_hashes);
  }

  pub fn with_perk_hashes(mut self, perk_hashes: Vec<i32>) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.perk_hashes = Some(perk_hashes);
    self
  }

  pub fn perk_hashes(&self) -> Option<&Vec<i32>> {
    self.perk_hashes.as_ref()
  }

  pub fn reset_perk_hashes(&mut self) {
    self.perk_hashes = None;
  }

  pub fn set_start_progression_bar_at_progress(&mut self, start_progression_bar_at_progress: i32) {
    self.start_progression_bar_at_progress = Some(start_progression_bar_at_progress);
  }

  pub fn with_start_progression_bar_at_progress(mut self, start_progression_bar_at_progress: i32) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.start_progression_bar_at_progress = Some(start_progression_bar_at_progress);
    self
  }

  pub fn start_progression_bar_at_progress(&self) -> Option<&i32> {
    self.start_progression_bar_at_progress.as_ref()
  }

  pub fn reset_start_progression_bar_at_progress(&mut self) {
    self.start_progression_bar_at_progress = None;
  }

  pub fn set_stat_hashes(&mut self, stat_hashes: Vec<i32>) {
    self.stat_hashes = Some(stat_hashes);
  }

  pub fn with_stat_hashes(mut self, stat_hashes: Vec<i32>) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.stat_hashes = Some(stat_hashes);
    self
  }

  pub fn stat_hashes(&self) -> Option<&Vec<i32>> {
    self.stat_hashes.as_ref()
  }

  pub fn reset_stat_hashes(&mut self) {
    self.stat_hashes = None;
  }

  pub fn set_affects_quality(&mut self, affects_quality: bool) {
    self.affects_quality = Some(affects_quality);
  }

  pub fn with_affects_quality(mut self, affects_quality: bool) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.affects_quality = Some(affects_quality);
    self
  }

  pub fn affects_quality(&self) -> Option<&bool> {
    self.affects_quality.as_ref()
  }

  pub fn reset_affects_quality(&mut self) {
    self.affects_quality = None;
  }

  pub fn set_step_groups(&mut self, step_groups: Value) {
    self.step_groups = Some(step_groups);
  }

  pub fn with_step_groups(mut self, step_groups: Value) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.step_groups = Some(step_groups);
    self
  }

  pub fn step_groups(&self) -> Option<&Value> {
    self.step_groups.as_ref()
  }

  pub fn reset_step_groups(&mut self) {
    self.step_groups = None;
  }

  pub fn set_affects_level(&mut self, affects_level: bool) {
    self.affects_level = Some(affects_level);
  }

  pub fn with_affects_level(mut self, affects_level: bool) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.affects_level = Some(affects_level);
    self
  }

  pub fn affects_level(&self) -> Option<&bool> {
    self.affects_level.as_ref()
  }

  pub fn reset_affects_level(&mut self) {
    self.affects_level = None;
  }

  pub fn set_socket_replacements(&mut self, socket_replacements: Vec<::models::DestinyDefinitionsDestinyNodeSocketReplaceResponse>) {
    self.socket_replacements = Some(socket_replacements);
  }

  pub fn with_socket_replacements(mut self, socket_replacements: Vec<::models::DestinyDefinitionsDestinyNodeSocketReplaceResponse>) -> DestinyDefinitionsDestinyNodeStepDefinition {
    self.socket_replacements = Some(socket_replacements);
    self
  }

  pub fn socket_replacements(&self) -> Option<&Vec<::models::DestinyDefinitionsDestinyNodeSocketReplaceResponse>> {
    self.socket_replacements.as_ref()
  }

  pub fn reset_socket_replacements(&mut self) {
    self.socket_replacements = None;
  }

}



