/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.7.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TrendingTrendingEntrySupportArticle {
  #[serde(rename = "article")]
  article: Option<::models::ContentContentItemPublicContract>
}

impl TrendingTrendingEntrySupportArticle {
  pub fn new() -> TrendingTrendingEntrySupportArticle {
    TrendingTrendingEntrySupportArticle {
      article: None
    }
  }

  pub fn set_article(&mut self, article: ::models::ContentContentItemPublicContract) {
    self.article = Some(article);
  }

  pub fn with_article(mut self, article: ::models::ContentContentItemPublicContract) -> TrendingTrendingEntrySupportArticle {
    self.article = Some(article);
    self
  }

  pub fn article(&self) -> Option<&::models::ContentContentItemPublicContract> {
    self.article.as_ref()
  }

  pub fn reset_article(&mut self) {
    self.article = None;
  }

}



